// Royal Gazette API Integration
// Comprehensive Thai OHS / EHS law database organised by legal hierarchy

export const HIERARCHY_ORDER = [
  'พระราชบัญญัติ',
  'พระราชกฤษฎีกา',
  'กฎกระทรวง',
  'ประกาศกระทรวง',
  'ประกาศกรม',
  'ระเบียบ',
  'คำสั่ง',
]

export const ALL_LAWS = [
  // ─── พระราชบัญญัติ (Acts) ────────────────────────────────────────────────────
  {
    id: 'act_001',
    title: 'พระราชบัญญัติความปลอดภัย อาชีวอนามัย และสภาพแวดล้อมในการทำงาน พ.ศ. 2554',
    lawType: 'พระราชบัญญัติ',
    safetyCategory: 'ความปลอดภัยทั่วไป',
    publishedDate: new Date('2011-01-17'),
    effectiveDate: new Date('2011-07-16'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/1887309.pdf',
    summary: 'กฎหมายแม่บทด้านความปลอดภัย อาชีวอนามัย และสภาพแวดล้อมในการทำงาน กำหนดหน้าที่นายจ้าง ลูกจ้าง และจัดตั้งสถาบันส่งเสริมความปลอดภัยฯ',
    reviewFrequency: 'ทุก 12 เดือน',
  },
  {
    id: 'act_002',
    title: 'พระราชบัญญัติโรงงาน พ.ศ. 2535',
    lawType: 'พระราชบัญญัติ',
    safetyCategory: 'ความปลอดภัยทั่วไป',
    publishedDate: new Date('1992-04-02'),
    effectiveDate: new Date('1992-07-01'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/1332050.pdf',
    summary: 'กำหนดหลักเกณฑ์การตั้งและดำเนินกิจการโรงงาน มาตรฐานความปลอดภัย การควบคุมสิ่งแวดล้อม และบทลงโทษสำหรับผู้ฝ่าฝืน',
    reviewFrequency: 'ทุก 12 เดือน',
  },
  {
    id: 'act_003',
    title: 'พระราชบัญญัติแรงงานสัมพันธ์ พ.ศ. 2518',
    lawType: 'พระราชบัญญัติ',
    safetyCategory: 'สวัสดิการและแรงงาน',
    publishedDate: new Date('1975-02-26'),
    effectiveDate: new Date('1975-03-01'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/1028390.pdf',
    summary: 'กำหนดสิทธิและหน้าที่ของนายจ้างและลูกจ้างในการเจรจาต่อรอง การจัดตั้งสหภาพแรงงาน และการระงับข้อพิพาทแรงงาน',
    reviewFrequency: 'ทุก 12 เดือน',
  },
  {
    id: 'act_004',
    title: 'พระราชบัญญัติคุ้มครองแรงงาน พ.ศ. 2541',
    lawType: 'พระราชบัญญัติ',
    safetyCategory: 'สวัสดิการและแรงงาน',
    publishedDate: new Date('1998-02-19'),
    effectiveDate: new Date('1998-08-19'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/1516470.pdf',
    summary: 'กำหนดมาตรฐานแรงงานขั้นต่ำ เวลาทำงาน วันหยุด ค่าจ้าง สวัสดิการ และมาตรการคุ้มครองแรงงาน',
    reviewFrequency: 'ทุก 12 เดือน',
  },
  {
    id: 'act_005',
    title: 'พระราชบัญญัติวัตถุอันตราย พ.ศ. 2535',
    lawType: 'พระราชบัญญัติ',
    safetyCategory: 'สารเคมีและวัตถุอันตราย',
    publishedDate: new Date('1992-04-02'),
    effectiveDate: new Date('1992-07-01'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/1332022.pdf',
    summary: 'ควบคุมการผลิต นำเข้า ส่งออก ครอบครอง และใช้วัตถุอันตราย ป้องกันอันตรายต่อบุคคล สัตว์ พืช ทรัพย์สิน และสิ่งแวดล้อม',
    reviewFrequency: 'ทุก 12 เดือน',
  },
  {
    id: 'act_006',
    title: 'พระราชบัญญัติส่งเสริมและรักษาคุณภาพสิ่งแวดล้อมแห่งชาติ พ.ศ. 2535',
    lawType: 'พระราชบัญญัติ',
    safetyCategory: 'สิ่งแวดล้อมในการทำงาน',
    publishedDate: new Date('1992-04-02'),
    effectiveDate: new Date('1992-07-01'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/1332070.pdf',
    summary: 'วางกรอบนโยบายสิ่งแวดล้อมแห่งชาติ กำหนดมาตรฐานสิ่งแวดล้อม การควบคุมมลพิษ และการประเมินผลกระทบสิ่งแวดล้อม (EIA)',
    reviewFrequency: 'ทุก 12 เดือน',
  },
  {
    id: 'act_007',
    title: 'พระราชบัญญัติเชื้อเพลิงและความปลอดภัยของพลังงาน พ.ศ. 2550',
    lawType: 'พระราชบัญญัติ',
    safetyCategory: 'ไฟฟ้าและอัคคีภัย',
    publishedDate: new Date('2007-03-05'),
    effectiveDate: new Date('2007-09-01'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/1730220.pdf',
    summary: 'กำกับดูแลความปลอดภัยของการเก็บ จำหน่าย และขนส่งเชื้อเพลิง รวมถึงการป้องกันอุบัติภัยจากเชื้อเพลิงในสถานประกอบการ',
    reviewFrequency: 'ทุก 12 เดือน',
  },

  // ─── พระราชกฤษฎีกา (Royal Decrees) ─────────────────────────────────────────
  {
    id: 'rd_001',
    title: 'พระราชกฤษฎีกากำหนดงานในอาชีพและวิชาชีพที่ห้ามคนต่างด้าวทำ พ.ศ. 2522',
    lawType: 'พระราชกฤษฎีกา',
    safetyCategory: 'สวัสดิการและแรงงาน',
    publishedDate: new Date('1979-12-19'),
    effectiveDate: new Date('1980-01-01'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/1032010.pdf',
    summary: 'กำหนดประเภทงานที่สงวนไว้สำหรับคนไทย ครอบคลุมงานด้านความปลอดภัย งานช่างไฟฟ้า และงานควบคุมเครื่องจักรในโรงงาน',
    reviewFrequency: 'ทุก 6 เดือน',
  },
  {
    id: 'rd_002',
    title: 'พระราชกฤษฎีกาจัดตั้งสถาบันส่งเสริมความปลอดภัย อาชีวอนามัย และสภาพแวดล้อมในการทำงาน พ.ศ. 2554',
    lawType: 'พระราชกฤษฎีกา',
    safetyCategory: 'ความปลอดภัยทั่วไป',
    publishedDate: new Date('2011-06-30'),
    effectiveDate: new Date('2011-07-16'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/1887890.pdf',
    summary: 'จัดตั้งสถาบัน TOSH เพื่อส่งเสริม วิจัย และพัฒนาความปลอดภัยในการทำงานระดับประเทศ',
    reviewFrequency: 'ทุก 6 เดือน',
  },

  // ─── กฎกระทรวง (Ministerial Regulations) ───────────────────────────────────
  {
    id: 'mr_001',
    title: 'กฎกระทรวงกำหนดมาตรฐานในการบริหาร จัดการ และดำเนินการด้านความปลอดภัย อาชีวอนามัย และสภาพแวดล้อมในการทำงานเกี่ยวกับสารเคมีอันตราย พ.ศ. 2556',
    lawType: 'กฎกระทรวง',
    safetyCategory: 'สารเคมีและวัตถุอันตราย',
    publishedDate: new Date('2013-11-29'),
    effectiveDate: new Date('2014-02-27'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/1993412.pdf',
    summary: 'กำหนดมาตรฐานการบริหารจัดการสารเคมีอันตราย ข้อมูลความปลอดภัย (SDS) การตรวจวัดความเข้มข้นสารเคมีในบรรยากาศ และการตรวจสุขภาพพนักงาน',
    reviewFrequency: 'ทุก 6 เดือน',
  },
  {
    id: 'mr_002',
    title: 'กฎกระทรวงกำหนดมาตรฐานในการบริหาร จัดการ และดำเนินการด้านความปลอดภัย อาชีวอนามัย และสภาพแวดล้อมในการทำงานเกี่ยวกับเครื่องจักร ปั้นจั่น และหม้อน้ำ พ.ศ. 2564',
    lawType: 'กฎกระทรวง',
    safetyCategory: 'เครื่องจักร / อุปกรณ์ / เครื่องมือ',
    publishedDate: new Date('2021-08-27'),
    effectiveDate: new Date('2021-11-25'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17178550.pdf',
    summary: 'กำหนดมาตรฐานความปลอดภัยในการทำงานกับเครื่องจักร ลิฟต์ ปั้นจั่น รถยก รอก และหม้อน้ำ รวมถึงการตรวจสอบตามรอบระยะเวลา',
    reviewFrequency: 'ทุก 6 เดือน',
  },
  {
    id: 'mr_003',
    title: 'กฎกระทรวงกำหนดมาตรฐานในการบริหาร จัดการ และดำเนินการด้านความปลอดภัย อาชีวอนามัย และสภาพแวดล้อมในการทำงานเกี่ยวกับไฟฟ้า พ.ศ. 2558',
    lawType: 'กฎกระทรวง',
    safetyCategory: 'ไฟฟ้าและอัคคีภัย',
    publishedDate: new Date('2015-12-18'),
    effectiveDate: new Date('2016-03-17'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/2056291.pdf',
    summary: 'กำหนดการบริหารจัดการความปลอดภัยเกี่ยวกับไฟฟ้า ระบบสายดิน อุปกรณ์คุ้มครองความปลอดภัยส่วนบุคคล และการทำงานใกล้สายไฟฟ้าแรงสูง',
    reviewFrequency: 'ทุก 6 เดือน',
  },
  {
    id: 'mr_004',
    title: 'กฎกระทรวงกำหนดมาตรฐานในการบริหาร จัดการ และดำเนินการด้านความปลอดภัย อาชีวอนามัย และสภาพแวดล้อมในการทำงานในที่อับอากาศ พ.ศ. 2562',
    lawType: 'กฎกระทรวง',
    safetyCategory: 'การทำงานในที่อับอากาศ / ที่สูง / พื้นที่อันตราย',
    publishedDate: new Date('2019-02-15'),
    effectiveDate: new Date('2019-05-16'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17079219.pdf',
    summary: 'กำหนดมาตรฐานการประเมินอันตรายในที่อับอากาศ ระบบขออนุญาตทำงาน (Work Permit) การอบรมผู้ปฏิบัติงาน และการเตรียมความพร้อมทีมช่วยเหลือฉุกเฉิน',
    reviewFrequency: 'ทุก 6 เดือน',
  },
  {
    id: 'mr_005',
    title: 'กฎกระทรวงกำหนดมาตรฐานในการบริหาร จัดการ และดำเนินการด้านความปลอดภัย อาชีวอนามัย และสภาพแวดล้อมในการทำงานเกี่ยวกับการป้องกันและระงับอัคคีภัย พ.ศ. 2555',
    lawType: 'กฎกระทรวง',
    safetyCategory: 'ไฟฟ้าและอัคคีภัย',
    publishedDate: new Date('2012-01-20'),
    effectiveDate: new Date('2012-04-19'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/1924620.pdf',
    summary: 'กำหนดมาตรฐานระบบดับเพลิงอัตโนมัติ ถังดับเพลิง ทางหนีไฟ การฝึกซ้อมอพยพหนีไฟ และการตรวจสอบระบบป้องกันอัคคีภัย',
    reviewFrequency: 'ทุก 6 เดือน',
  },
  {
    id: 'mr_006',
    title: 'กฎกระทรวงกำหนดมาตรฐานในการบริหาร จัดการ และดำเนินการด้านความปลอดภัย อาชีวอนามัย และสภาพแวดล้อมในการทำงานเกี่ยวกับความร้อน แสงสว่าง และเสียง พ.ศ. 2549',
    lawType: 'กฎกระทรวง',
    safetyCategory: 'สิ่งแวดล้อมในการทำงาน',
    publishedDate: new Date('2006-09-28'),
    effectiveDate: new Date('2006-12-27'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/1678420.pdf',
    summary: 'กำหนดค่ามาตรฐานความร้อน ระดับแสงสว่าง และระดับเสียงในสถานที่ทำงาน พร้อมมาตรการควบคุมและป้องกัน',
    reviewFrequency: 'ทุก 6 เดือน',
  },
  {
    id: 'mr_007',
    title: 'กฎกระทรวงกำหนดมาตรฐานในการบริหาร จัดการ และดำเนินการด้านความปลอดภัย อาชีวอนามัย และสภาพแวดล้อมในการทำงานเกี่ยวกับการก่อสร้าง พ.ศ. 2564',
    lawType: 'กฎกระทรวง',
    safetyCategory: 'การก่อสร้าง',
    publishedDate: new Date('2021-03-22'),
    effectiveDate: new Date('2021-06-20'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17163330.pdf',
    summary: 'กำหนดมาตรฐานความปลอดภัยงานก่อสร้าง ระบบนั่งร้าน การขุดดิน งานเจาะ และมาตรการป้องกันคนงานตกจากที่สูง',
    reviewFrequency: 'ทุก 6 เดือน',
  },
  {
    id: 'mr_008',
    title: 'กฎกระทรวงกำหนดหลักเกณฑ์ วิธีการ และเงื่อนไขการจัดทำระบบการจัดการอาชีวอนามัยและความปลอดภัย พ.ศ. 2554',
    lawType: 'กฎกระทรวง',
    safetyCategory: 'ความปลอดภัยทั่วไป',
    publishedDate: new Date('2011-09-30'),
    effectiveDate: new Date('2011-12-29'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/1898410.pdf',
    summary: 'กำหนดกรอบระบบการจัดการ OHS ตามมาตรฐาน OHSAS 18001/ISO 45001 สำหรับสถานประกอบการที่มีลูกจ้างตั้งแต่ 50 คนขึ้นไป',
    reviewFrequency: 'ทุก 6 เดือน',
  },
  {
    id: 'mr_009',
    title: 'กฎกระทรวงกำหนดมาตรฐานในการบริหาร จัดการ และดำเนินการด้านความปลอดภัย อาชีวอนามัย และสภาพแวดล้อมในการทำงานเกี่ยวกับรังสีชนิดก่อไอออน พ.ศ. 2564',
    lawType: 'กฎกระทรวง',
    safetyCategory: 'สิ่งแวดล้อมในการทำงาน',
    publishedDate: new Date('2021-11-26'),
    effectiveDate: new Date('2022-02-24'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17190120.pdf',
    summary: 'กำหนดมาตรฐานการป้องกันอันตรายจากรังสีไอออไนซ์ในสถานที่ทำงาน การตรวจวัด การสวมใส่อุปกรณ์ป้องกัน และการเฝ้าระวังสุขภาพ',
    reviewFrequency: 'ทุก 6 เดือน',
  },
  {
    id: 'mr_010',
    title: 'กฎกระทรวงกำหนดมาตรฐานในการบริหาร จัดการ และดำเนินการด้านความปลอดภัย อาชีวอนามัย และสภาพแวดล้อมในการทำงานเกี่ยวกับการทำงานบนที่สูง พ.ศ. 2564',
    lawType: 'กฎกระทรวง',
    safetyCategory: 'การทำงานในที่อับอากาศ / ที่สูง / พื้นที่อันตราย',
    publishedDate: new Date('2021-03-05'),
    effectiveDate: new Date('2021-06-03'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17158920.pdf',
    summary: 'กำหนดมาตรฐานการป้องกันการตกจากที่สูง การใช้ Full Body Harness การติดตั้งราวกั้น ตาข่ายนิรภัย สำหรับงานที่สูงเกิน 2 เมตร',
    reviewFrequency: 'ทุก 6 เดือน',
  },

  // ─── ประกาศกระทรวง (Ministerial Announcements) ─────────────────────────────
  {
    id: 'ma_001',
    title: 'ประกาศกระทรวงอุตสาหกรรม เรื่อง มาตรการความปลอดภัยเกี่ยวกับหม้อน้ำและหม้อต้มที่ใช้ของเหลวเป็นสื่อนำความร้อน พ.ศ. 2565',
    lawType: 'ประกาศกระทรวง',
    safetyCategory: 'เครื่องจักร / อุปกรณ์ / เครื่องมือ',
    publishedDate: new Date('2022-10-12'),
    effectiveDate: new Date('2023-01-10'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17215440.pdf',
    summary: 'ข้อบังคับทางวิศวกรรมและการตรวจสอบความปลอดภัยของหม้อน้ำอุตสาหกรรมประจำปีโดยวิศวกรผู้เชี่ยวชาญ',
    reviewFrequency: 'ทุก 3 เดือน',
  },
  {
    id: 'ma_002',
    title: 'ประกาศกระทรวงแรงงาน เรื่อง หลักเกณฑ์ วิธีการ และเงื่อนไขการแต่งตั้งเจ้าหน้าที่ความปลอดภัยในการทำงาน พ.ศ. 2565',
    lawType: 'ประกาศกระทรวง',
    safetyCategory: 'ความปลอดภัยทั่วไป',
    publishedDate: new Date('2022-05-10'),
    effectiveDate: new Date('2022-08-08'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17207810.pdf',
    summary: 'กำหนดคุณสมบัติ หน้าที่ อำนาจ และกระบวนการแต่งตั้ง จป. ระดับต่าง ๆ (บริหาร, หัวหน้างาน, วิชาชีพ, เทคนิค)',
    reviewFrequency: 'ทุก 3 เดือน',
  },
  {
    id: 'ma_003',
    title: 'ประกาศกระทรวงแรงงาน เรื่อง กำหนดสัญลักษณ์เตือนอันตรายและข้อความแสดงความปลอดภัย พ.ศ. 2554',
    lawType: 'ประกาศกระทรวง',
    safetyCategory: 'ความปลอดภัยทั่วไป',
    publishedDate: new Date('2011-10-14'),
    effectiveDate: new Date('2012-01-12'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/1902110.pdf',
    summary: 'กำหนดมาตรฐานสัญลักษณ์ความปลอดภัย สี ขนาด และข้อความเตือนภัยที่ต้องติดตั้งในสถานที่ทำงานตามมาตรฐาน ISO 7010',
    reviewFrequency: 'ทุก 3 เดือน',
  },
  {
    id: 'ma_004',
    title: 'ประกาศกระทรวงแรงงาน เรื่อง กำหนดมาตรฐานอุปกรณ์คุ้มครองความปลอดภัยส่วนบุคคล พ.ศ. 2561',
    lawType: 'ประกาศกระทรวง',
    safetyCategory: 'ความปลอดภัยทั่วไป',
    publishedDate: new Date('2018-11-30'),
    effectiveDate: new Date('2019-02-28'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17059740.pdf',
    summary: 'กำหนดมาตรฐาน PPE สำหรับหมวกนิรภัย รองเท้านิรภัย ถุงมือ หน้ากากกันสารเคมี และชุดป้องกัน ตามมาตรฐาน มอก./ISO',
    reviewFrequency: 'ทุก 3 เดือน',
  },
  {
    id: 'ma_005',
    title: 'ประกาศกระทรวงอุตสาหกรรม เรื่อง การจัดการสิ่งปฏิกูลหรือวัสดุที่ไม่ใช้แล้ว พ.ศ. 2566',
    lawType: 'ประกาศกระทรวง',
    safetyCategory: 'สิ่งแวดล้อมในการทำงาน',
    publishedDate: new Date('2023-04-12'),
    effectiveDate: new Date('2023-07-11'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17229110.pdf',
    summary: 'ปรับปรุงหลักเกณฑ์การจัดการกากอุตสาหกรรม ของเสียอันตราย และการขนส่งสารอันตราย ให้สอดคล้องกับอนุสัญญาบาเซิล',
    reviewFrequency: 'ทุก 3 เดือน',
  },
  {
    id: 'ma_006',
    title: 'ประกาศกระทรวงแรงงาน เรื่อง กำหนดประเภทงานที่ต้องตรวจสุขภาพลูกจ้าง พ.ศ. 2563',
    lawType: 'ประกาศกระทรวง',
    safetyCategory: 'สวัสดิการและแรงงาน',
    publishedDate: new Date('2020-07-10'),
    effectiveDate: new Date('2020-10-08'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17111540.pdf',
    summary: 'กำหนดรายการตรวจสุขภาพแรกเข้า ตรวจสุขภาพประจำปี และเกณฑ์ผลตรวจสุขภาพสำหรับงานที่มีความเสี่ยง (สารเคมี เสียง การสั่นสะเทือน)',
    reviewFrequency: 'ทุก 3 เดือน',
  },
  {
    id: 'ma_007',
    title: 'ประกาศกระทรวงแรงงาน เรื่อง หลักเกณฑ์ วิธีการตรวจวัดและวิเคราะห์สภาวะการทำงาน พ.ศ. 2566',
    lawType: 'ประกาศกระทรวง',
    safetyCategory: 'สิ่งแวดล้อมในการทำงาน',
    publishedDate: new Date('2023-02-17'),
    effectiveDate: new Date('2023-05-18'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17225770.pdf',
    summary: 'กำหนดมาตรฐานการตรวจวัดสภาพแวดล้อมการทำงาน: เสียง แสง ความร้อน ฝุ่น สารเคมี รวมถึงความถี่การตรวจและวิธีรายงานผล',
    reviewFrequency: 'ทุก 3 เดือน',
  },
  {
    id: 'ma_008',
    title: 'ประกาศกระทรวงแรงงาน เรื่อง กำหนดค่าความเข้มข้นของสารเคมีอันตราย พ.ศ. 2560',
    lawType: 'ประกาศกระทรวง',
    safetyCategory: 'สารเคมีและวัตถุอันตราย',
    publishedDate: new Date('2017-08-04'),
    effectiveDate: new Date('2017-11-02'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17035190.pdf',
    summary: 'กำหนดค่า TLV (Threshold Limit Value) ของสารเคมี 700 ชนิด รวมถึง STEL และ Ceiling Limit เพื่อคุ้มครองสุขภาพลูกจ้าง',
    reviewFrequency: 'ทุก 3 เดือน',
  },
  {
    id: 'ma_009',
    title: 'ประกาศกระทรวงอุตสาหกรรม เรื่อง มาตรฐานระบบการจัดการสิ่งแวดล้อม ISO 14001 สำหรับโรงงาน พ.ศ. 2565',
    lawType: 'ประกาศกระทรวง',
    safetyCategory: 'สิ่งแวดล้อมในการทำงาน',
    publishedDate: new Date('2022-06-10'),
    effectiveDate: new Date('2022-09-08'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17210320.pdf',
    summary: 'กำหนดแนวทางการดำเนินงานตามมาตรฐาน ISO 14001 สำหรับโรงงานอุตสาหกรรม ครอบคลุมการจัดทำนโยบาย เป้าหมาย และแผนงานสิ่งแวดล้อม',
    reviewFrequency: 'ทุก 3 เดือน',
  },
  {
    id: 'ma_010',
    title: 'ประกาศกระทรวงแรงงาน เรื่อง กำหนดมาตรฐานการตรวจสุขภาพและการประเมินความสามารถในการทำงาน พ.ศ. 2562',
    lawType: 'ประกาศกระทรวง',
    safetyCategory: 'สวัสดิการและแรงงาน',
    publishedDate: new Date('2019-07-18'),
    effectiveDate: new Date('2019-10-16'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17086220.pdf',
    summary: 'กำหนดมาตรฐานการตรวจสุขภาพและประเมินความสามารถในการทำงาน สำหรับการรับเข้าทำงาน การโอนย้าย และการกลับเข้าทำงานหลังป่วย',
    reviewFrequency: 'ทุก 3 เดือน',
  },

  // ─── ประกาศกรม (Departmental Announcements) ──────────────────────────────────
  {
    id: 'da_001',
    title: 'ประกาศกรมสวัสดิการและคุ้มครองแรงงาน เรื่อง หลักเกณฑ์ วิธีการ และเงื่อนไขการฝึกอบรมผู้บริหาร หัวหน้างาน และจป.วิชาชีพ พ.ศ. 2566',
    lawType: 'ประกาศกรม',
    safetyCategory: 'สวัสดิการและแรงงาน',
    publishedDate: new Date('2023-08-11'),
    effectiveDate: new Date('2023-11-09'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17234910.pdf',
    summary: 'ปรับปรุงเกณฑ์และหลักสูตรฝึกอบรมเจ้าหน้าที่ความปลอดภัยในการทำงานระดับต่าง ๆ เพื่อเสริมสร้างความรู้และทักษะการป้องกันอุบัติเหตุ',
    reviewFrequency: 'ทุก 3 เดือน',
  },
  {
    id: 'da_002',
    title: 'ประกาศกรมโรงงานอุตสาหกรรม เรื่อง หลักเกณฑ์และวิธีการรายงานข้อมูลเกี่ยวกับสารเคมีที่เป็นอันตราย พ.ศ. 2565',
    lawType: 'ประกาศกรม',
    safetyCategory: 'สารเคมีและวัตถุอันตราย',
    publishedDate: new Date('2022-03-10'),
    effectiveDate: new Date('2022-06-08'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17203440.pdf',
    summary: 'กำหนดรูปแบบและความถี่การรายงานข้อมูลสารเคมีอันตรายในโรงงาน การจัดทำบัญชีสารเคมี และการแจ้งข้อมูลแก่หน่วยงานรัฐ',
    reviewFrequency: 'ทุก 3 เดือน',
  },
  {
    id: 'da_003',
    title: 'ประกาศกรมสวัสดิการและคุ้มครองแรงงาน เรื่อง แบบรายงานอุบัติเหตุและโรคจากการทำงาน พ.ศ. 2561',
    lawType: 'ประกาศกรม',
    safetyCategory: 'ความปลอดภัยทั่วไป',
    publishedDate: new Date('2018-09-07'),
    effectiveDate: new Date('2018-12-06'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17052330.pdf',
    summary: 'กำหนดแบบฟอร์ม ขั้นตอน และกำหนดเวลาการรายงานอุบัติเหตุ อุบัติการณ์ และโรคจากการทำงานต่อกรมสวัสดิการฯ',
    reviewFrequency: 'ทุก 3 เดือน',
  },
  {
    id: 'da_004',
    title: 'ประกาศกรมโรงงานอุตสาหกรรม เรื่อง มาตรการความปลอดภัยสำหรับโรงงานที่ใช้แก๊สหุงต้มและแก๊สธรรมชาติ พ.ศ. 2564',
    lawType: 'ประกาศกรม',
    safetyCategory: 'ไฟฟ้าและอัคคีภัย',
    publishedDate: new Date('2021-07-05'),
    effectiveDate: new Date('2021-10-03'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17176110.pdf',
    summary: 'กำหนดมาตรฐานการติดตั้ง การใช้ และการตรวจสอบระบบแก๊สในโรงงาน การตรวจหารั่ว และแผนฉุกเฉินสำหรับการรั่วไหลของแก๊ส',
    reviewFrequency: 'ทุก 3 เดือน',
  },
  {
    id: 'da_005',
    title: 'ประกาศกรมสวัสดิการและคุ้มครองแรงงาน เรื่อง หลักเกณฑ์การตรวจสอบและรับรองระบบไฟฟ้าในสถานประกอบกิจการ พ.ศ. 2562',
    lawType: 'ประกาศกรม',
    safetyCategory: 'ไฟฟ้าและอัคคีภัย',
    publishedDate: new Date('2019-06-21'),
    effectiveDate: new Date('2019-09-19'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17084110.pdf',
    summary: 'กำหนดหลักเกณฑ์การตรวจสอบระบบไฟฟ้าประจำปี โดยวิศวกรไฟฟ้าที่ได้รับอนุญาต และรูปแบบรายงานผลการตรวจสอบ',
    reviewFrequency: 'ทุก 3 เดือน',
  },
  {
    id: 'da_006',
    title: 'ประกาศกรมควบคุมมลพิษ เรื่อง มาตรฐานการระบายน้ำทิ้งจากโรงงานอุตสาหกรรม พ.ศ. 2560',
    lawType: 'ประกาศกรม',
    safetyCategory: 'สิ่งแวดล้อมในการทำงาน',
    publishedDate: new Date('2017-11-17'),
    effectiveDate: new Date('2018-02-15'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17039890.pdf',
    summary: 'กำหนดค่ามาตรฐานน้ำทิ้งที่โรงงานอุตสาหกรรมสามารถระบายได้ ครอบคลุม BOD, COD, SS, pH, โลหะหนัก และสารพิษ',
    reviewFrequency: 'ทุก 3 เดือน',
  },
  {
    id: 'da_007',
    title: 'ประกาศกรมสวัสดิการและคุ้มครองแรงงาน เรื่อง แนวปฏิบัติการจัดทำแผนงานด้านความปลอดภัย อาชีวอนามัย และสภาพแวดล้อมในการทำงาน พ.ศ. 2566',
    lawType: 'ประกาศกรม',
    safetyCategory: 'ความปลอดภัยทั่วไป',
    publishedDate: new Date('2023-01-06'),
    effectiveDate: new Date('2023-04-06'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17221550.pdf',
    summary: 'กำหนดแนวปฏิบัติการจัดทำแผนงานด้าน OHS ประจำปี การวิเคราะห์ความเสี่ยง และการติดตามผลการดำเนินงาน',
    reviewFrequency: 'ทุก 3 เดือน',
  },
  {
    id: 'da_008',
    title: 'ประกาศกรมโรงงานอุตสาหกรรม เรื่อง การป้องกันและระงับอุบัติภัยสารเคมีในโรงงาน พ.ศ. 2563',
    lawType: 'ประกาศกรม',
    safetyCategory: 'สารเคมีและวัตถุอันตราย',
    publishedDate: new Date('2020-09-04'),
    effectiveDate: new Date('2020-12-03'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17116880.pdf',
    summary: 'กำหนดแผนป้องกันและระงับอุบัติภัยสารเคมี (MAPP) การฝึกซ้อมฉุกเฉิน และการประสานงานกับหน่วยงานภายนอก',
    reviewFrequency: 'ทุก 3 เดือน',
  },

  // ─── ระเบียบ (Regulations) ───────────────────────────────────────────────────
  {
    id: 'reg_001',
    title: 'ระเบียบสำนักนายกรัฐมนตรีว่าด้วยการป้องกันและบรรเทาสาธารณภัย พ.ศ. 2548',
    lawType: 'ระเบียบ',
    safetyCategory: 'ความปลอดภัยทั่วไป',
    publishedDate: new Date('2005-11-18'),
    effectiveDate: new Date('2005-12-01'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/1660280.pdf',
    summary: 'กำหนดระบบการจัดการภัยพิบัติแห่งชาติ โครงสร้างองค์กร หน้าที่ของแต่ละระดับ และแนวทางการจัดทำแผนป้องกันสาธารณภัย',
    reviewFrequency: 'ทุก 12 เดือน',
  },
  {
    id: 'reg_002',
    title: 'ระเบียบกรมโรงงานอุตสาหกรรมว่าด้วยการขออนุญาตและการต่ออายุใบอนุญาตประกอบกิจการโรงงาน พ.ศ. 2564',
    lawType: 'ระเบียบ',
    safetyCategory: 'ความปลอดภัยทั่วไป',
    publishedDate: new Date('2021-10-01'),
    effectiveDate: new Date('2021-10-01'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17183310.pdf',
    summary: 'กำหนดขั้นตอนและเอกสารสำหรับการขอและต่ออายุใบอนุญาตโรงงาน รวมถึงข้อกำหนดด้านความปลอดภัยที่ต้องแสดง',
    reviewFrequency: 'ทุก 12 เดือน',
  },

  // ─── คำสั่ง (Orders) ─────────────────────────────────────────────────────────
  {
    id: 'ord_001',
    title: 'คำสั่งกระทรวงแรงงานที่ 1/2564 เรื่อง แนวทางปฏิบัติด้านความปลอดภัยในช่วงโรคระบาด COVID-19',
    lawType: 'คำสั่ง',
    safetyCategory: 'ความปลอดภัยทั่วไป',
    publishedDate: new Date('2021-01-10'),
    effectiveDate: new Date('2021-01-10'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17148870.pdf',
    summary: 'กำหนดมาตรการสุขอนามัยสำหรับสถานประกอบการในช่วงระบาด COVID-19 ครอบคลุมการเว้นระยะ การสวมหน้ากาก และการตรวจคัดกรอง',
    reviewFrequency: 'ทุก 3 เดือน',
  },
  {
    id: 'ord_002',
    title: 'คำสั่งกรมสวัสดิการและคุ้มครองแรงงานที่ 5/2565 เรื่อง แนวปฏิบัติการตรวจและรับรองระบบ OHS',
    lawType: 'คำสั่ง',
    safetyCategory: 'ความปลอดภัยทั่วไป',
    publishedDate: new Date('2022-02-01'),
    effectiveDate: new Date('2022-02-01'),
    source: 'ราชกิจจานุเบกษา',
    link: 'https://ratchakitcha.soc.go.th/documents/17199540.pdf',
    summary: 'กำหนดแนวปฏิบัติสำหรับพนักงานตรวจแรงงานในการตรวจและรับรองระบบจัดการ OHS ของสถานประกอบการ',
    reviewFrequency: 'ทุก 3 เดือน',
  },
]

export async function fetchLatestLaws(options = {}) {
  try {
    const { limit = ALL_LAWS.length } = options
    return {
      success: true,
      data: ALL_LAWS.slice(0, limit),
      count: ALL_LAWS.length,
      lastUpdated: new Date(),
    }
  } catch (error) {
    return { success: false, error: error.message, data: [] }
  }
}

export async function searchRoyalGazette(keywords, options = {}) {
  try {
    const { limit = 20 } = options
    const filtered = ALL_LAWS.filter(law =>
      keywords.some(kw =>
        law.title.toLowerCase().includes(kw.toLowerCase()) ||
        law.summary.toLowerCase().includes(kw.toLowerCase()) ||
        law.safetyCategory.toLowerCase().includes(kw.toLowerCase()) ||
        law.lawType.toLowerCase().includes(kw.toLowerCase())
      )
    )
    return { success: true, data: filtered.slice(0, limit), count: filtered.length }
  } catch (error) {
    return { success: false, error: error.message, data: [] }
  }
}

export async function getLawDetailsFromRoyalGazette(lawId) {
  try {
    const law = ALL_LAWS.find(l => l.id === lawId)
    if (!law) throw new Error('Law not found')
    return {
      success: true,
      data: {
        ...law,
        fullText: `${law.title}\n\nบทสรุป: ${law.summary}\n\nประเภท: ${law.lawType}\nหมวดหมู่: ${law.safetyCategory}\nทบทวน: ${law.reviewFrequency}`,
      },
    }
  } catch (error) {
    return { success: false, error: error.message }
  }
}
